### ISSUE TITLE
App does not scale nicely to mobile viewports

### ISSUE THREAD

**Issue by charleslimjh** [charleslimjh/Kachow#8]
1. Navbar overlaps with body content, we need to add a solid background to the navbar to cover the body content.
2. The navbar cannot be closed once opened.
3. Some elements do not scale to mobile nicely.

**Comment by charleslimjh** [comment]
Additional suggestion: we should change all the navbars to be `class="navbar-dark bg-dark"` for greater contrast against the white background.

**Comment by xinnnyuuu** [comment]
Design looks better without styling it black.
